### ISSUE TITLE
Rework Thread and Communication concept

### ISSUE THREAD

**Issue by huebl** [ASNeG/OpcUaStack#11]
The thread is currently single threaded. This is problematic in several ways.

- The processing of slow tasks blocks other tasks

- The application uses the same thread as the SDK.

- The processor is not used optimally

**Comment by huebl** [comment]
In all Software components of the application a uniform thread concept should be used. This concept should support the following concepts.

- All operations should be performed by non-blocking tasks.
- All operations are inserted into a queue and executed by one or more threads.

The following operations are supported.

- Asynchronous tasks
- Timer tasks
- Socket Tasks
- Message Tasks

**Comment by huebl** [comment]
If an application consists of several software components, there are often dependencies between the software components during startup. A software component can go through several init states during startup. These dependencies between the software components should be able to be set using the configuration file.

**Comment by huebl** [comment]
With this issue, a concept should first be worked out.

**Comment by huebl** [comment]
In the first step, only a documentation is to be created.

**Comment by flipback** [comment]
> `The thread is currently single threaded. This is problematic in several 

Do you meen OPC UA Session instead of "thread"?

**Comment by huebl** [comment]
This feature is to be implemented with Issue #339. For this reason the feature is closed.
