### ISSUE TITLE
Incorrect apt-get install command

### ISSUE THREAD

**Issue by strowk** [ASNeG/OpcUaStack#128]
Documentation
https://opcuastack.readthedocs.io/en/latest/getting_started/installation.html
asks to execute following command
```
sudo apt-get install apt-get install libboost-all-dev cmake libssl-dev  build-essential
```
but it should not contain second `apt-get install`.

**Comment by flipback** [comment]
Hi, @strowk! Thanks for your report! We'll fix it ASAP.
