### ISSUE TITLE
Default installation path conflicts with default expectation

### ISSUE THREAD

**Issue by strowk** [ASNeG/OpcUaStack#129]
By default from sources all would be installed
https://opcuastack.readthedocs.io/en/latest/getting_started/installation.html
to 
`~/.ASNeG`
, which would require from user to do something like 
```
export PATH=$HOME/.ASNeG/usr/bin:$PATH
export LD_LIBRARY_PATH=$HOME/.ASNeG/usr/lib:$LD_LIBRARY_PATH
```
and it still would not really help, because when doing
https://opcuastack.readthedocs.io/en/latest/getting_started/hello_world.html
user would get the
```
CMake Error at CMakeLists.txt:82 (include):
  include could not find load file:

    /usr/share/cmake/OpcUaStack3/CMakeOpenSSL.txt
```

So either detailed explanation how to not get rid of these problems should be included in documentation (what to add to .bashrc, how to configure currently opened shell, etc) or default path should be `/` instead `~/.ASNeG`. It seems that application is designed to be installed to root...

**Comment by flipback** [comment]
Hi, @strowk! You are right, there is some lack of information in Hello World example.

The stack is designed to be installed in different ways. 

* Local (by default ~/.ASNeG)
* DEB
* RPM
* MSI
* Docker

When you build your application for local installation we make suggestion what you installed the stack to root by using DEB or RPM packets and this command should work correct: 
 
```sh build.sh -t local -i path/to/install``` 

If you've installed the stack locally, you should pass the path with -s option:

```sh build.sh -t local -i path/to/install -s ~/.ASNeG```

We'll correct it in the example. 

Actually we're only beginning to document the stack and I'm planning to write a special document to explain how users can compile and distribute their applications.

Thanks again for your contribution!
