### ISSUE TITLE
Merge master branch to Release4 branch 

### ISSUE THREAD

**Issue by huebl** [ASNeG/OpcUaStack#167]
Work on Release 3.7 is complete. The resolved bugs, feature and documentation should be transferred to version 4.

**Comment by flipback** [comment]
Hi, @huebl! I don't think our users (including my company) will be happy if they are forced to port their applications to version 4 because of a bug in version 3. We must be responsible for our users  and support major releases with bug-fixes for a some time.

**Comment by huebl** [comment]
Hi @flipback, of course we will continue to maintain version 3. The issue is just to fix the issues fixed in Release 3 in version 4 as well.

**Comment by flipback** [comment]
Ok. I just misunderstood the description.
