### ISSUE TITLE
Make PolicyId in opc ua client configureable

### ISSUE THREAD

**Issue by huebl** [ASNeG/OpcUaStack#168]
When client connect as anonymous, it send anonymousIdentityToken, that hardcoded in \src\OpcUaStackClient\ServiceSet\SessionService.cpp:392 as

```
anonymousIdentityToken->policyId("Anonymous_Policy");
```

The PolicyId should be configurable in the opc ua client stack.

**Comment by flipback** [comment]
The issue is solved in the 3.7.1, but it's not a bug. I suggest replacing changes to Release4.
