### ISSUE TITLE
Server doen't send CloseSecureChannelResponse

### ISSUE THREAD

**Issue by flipback** [ASNeG/OpcUaStack#258]
**Describe the bug**

Judging by Wireshark dump the stack doesn't answer `CloseSecureChannel` request.

**Expected behavior**

According to the specification (Part 4, 5.5.3) a server must send an empty response with a header.

**Logs**

Wireshark dump - [ws_opcua_expert_connection.zip](https://github.com/ASNeG/OpcUaStack/files/3357893/ws_opcua_expert_connection.zip)

**Environment (please complete the following information):**
 - OS:  any
 - Version: 3.7.0

**Comment by huebl** [comment]
The Server does not send a CloseSecureChannel response.

See Part 4 5.5.3.2 and Part 6 7.1.4
