### ISSUE TITLE
OpcUaStackClient::Client crushes when remote server shuts down.

### ISSUE THREAD

**Issue by TYZzzzzzz** [ASNeG/OpcUaStack#302]
**Description**
If the Client tries to connect to unreachable server - the Client crushes.
If a remote server, the Client already connected to, shuts down - the Client crushes.

According to one test, if a remote server shuts down, after the Client succesfully disconnects from it - the Client crushes anyway (possibly on destructor call).

**To Reproduce**
1. Start OpcUaServer.
2. Connect Client to server.
3. Stop the server.
4. The client will crush.

**Expected behavior**
Client should not crush.

**Screenshots**
![error_screenshot1](https://user-images.githubusercontent.com/44251203/65755782-3cb84d00-e12d-11e9-9e5f-aa3cb40ae8eb.JPG)
![error_screenshot2](https://user-images.githubusercontent.com/44251203/65755798-43df5b00-e12d-11e9-9583-073407c7c0bb.JPG)

**Logs**
[connect_to_unreachable_server.log](https://github.com/ASNeG/OpcUaStack/files/3661824/connect_to_unreachable_server.log)
[shut_down_connected_server.log](https://github.com/ASNeG/OpcUaStack/files/3661826/shut_down_connected_server.log)

**Environment (please complete the following information):**
- ОС Windows 7 x64 SP1, repeats on Windows 10 too
- boost 1.58
- OpcUaStack v. 3 from master branch
- MSVC compiler

**Additional**
My Client wrapper implementation:
[opc_ua_client_helper.cpp.txt](https://github.com/ASNeG/OpcUaStack/files/3661857/opc_ua_client_helper.cpp.txt)

**Comment by huebl** [comment]
@TYZzzzzzz  - Do you also use version 3 for the client or only for the server?

**Comment by huebl** [comment]
I did tests with the opc ua stack version 3. There was no crash.

**Comment by huebl** [comment]
I did the following tests with an OPC UA client (version 3) on Linux.

Test 1:
1. Startup opc ua server
2. Startup opc ua client
3. Stop opc ua server
4. Start opc ua server

Test 2:
1. Startup opc ua client
2. Startup opc ua server

Result: The behavior of the OPC UA client and the OPC Ua server is correct.

**Comment by huebl** [comment]
@TYZzzzzzz - I can not repeat the mistake you described.

Can you create a small OPC UA client program with which I can reproduce the error?

**Comment by TYZzzzzzz** [comment]
I didn't perform tests on Linux, at this moment my target platform is Windows, but I'll try to test Linux version tomorrow

Before creating of this issue, I've tested with Google testing framework the minimal program like this
```cpp
TEST_F(OpcUaClientHelperTest, shouldWorksNormallyThenConnectingToUnreachableServer) {
    // init my client helper with concrete ip on SetUp phase
    // client is std::shared_ptr<OpcUaClientHelper>, I've attached implementation of this
    // helper to issue description as `opc_ua_client_helper.cpp.txt`

    // at this moment target server is unreachable
    client->Connect();
    std::this_thread::sleep_for(std::chrono::seconds{10});

    // without sleeping test finishes succesfully
    // but with `sleep` it crushes after 1-2 seconds with assertion error in
    // boost::shared_ptr on Debug build version
}
```

**Comment by huebl** [comment]
For the analysis of the error a small test program would help me a lot. The test program should run on Linux and optionally on Windows and should be able to be started from the command line. Only if I can reproduce the mistake, it is possible for me to help you specifically.

**Comment by TYZzzzzzz** [comment]
so, I performed test on Linux and got the same error

I prepared a minimal testing program: https://github.com/TYZzzzzzz/minimalClientTesting.git

I'm using an outer pre-builded dependencies - Boost and Stack, if it isn't usable for you, tomorrow I can expand it further

**Comment by huebl** [comment]
@TYZzzzzzz - Thanks for your support.

At the session level and in the SecureChannel level, timers are used. Sessionless connections use the OpenSecureChannel timers. Connections with a session use the session level timers. If the timers are active in both planes, this leads to a crash.

**Workaround:**
Disable the timer of the SecureChannel level. The error should then no longer occur.

```
    void InitSessionServiceConfig() {
        // init default configs for session
        CryptoManager::SPtr cryptoManager = constructSPtr<CryptoManager>();
        sec_srvc_cfg_.secureChannelClient_->cryptoManager(cryptoManager);
        sec_srvc_cfg_.secureChannelClient_->connectTimeout(2400000);
        //sec_srvc_cfg_.secureChannelClient_->reconnectTimeout(1024);
        sec_srvc_cfg_.secureChannelClient_->securityMode(SecurityMode::SM_None);
        sec_srvc_cfg_.secureChannelClient_->securityPolicy(SecurityPolicy::SP_None);

        sec_srvc_cfg_.ioThreadName("Serverio Client " + ip_ + " session thread");
        sec_srvc_cfg_.mode_ = SessionService::Mode::M_SecureChannelAndSession;

        sec_srvc_cfg_.sessionServiceIf_ = new SessionServiceStub();

        sec_srvc_cfg_.session_->sessionName("Client " + ip_ + " session");
    }

```

The session timer is activated by default if a session exists (Default is 3 seconds).  The session timer can be set as follows.

```
   void InitSessionServiceConfig() {
        // init default configs for session
        CryptoManager::SPtr cryptoManager = constructSPtr<CryptoManager>();
        sec_srvc_cfg_.secureChannelClient_->cryptoManager(cryptoManager);
        sec_srvc_cfg_.secureChannelClient_->connectTimeout(2400000);
        //sec_srvc_cfg_.secureChannelClient_->reconnectTimeout(1024);
        sec_srvc_cfg_.session_->reconnectTimeout(1024);
        sec_srvc_cfg_.secureChannelClient_->securityMode(SecurityMode::SM_None);
        sec_srvc_cfg_.secureChannelClient_->securityPolicy(SecurityPolicy::SP_None);

        sec_srvc_cfg_.ioThreadName("Serverio Client " + ip_ + " session thread");
        sec_srvc_cfg_.mode_ = SessionService::Mode::M_SecureChannelAndSession;

        sec_srvc_cfg_.sessionServiceIf_ = new SessionServiceStub();

        sec_srvc_cfg_.session_->sessionName("Client " + ip_ + " session");
    }
```

**ToDo:**
In the session, the timer of the OpenSecureChanel level must be deactivated automatically if a session timer exists.

**Comment by TYZzzzzzz** [comment]
@huebl Thanks for helping, the problem was fixed
