### ISSUE TITLE
OPC UA application is not avaliable by hostname

### ISSUE THREAD

**Issue by flipback** [ASNeG/OpcUaStack#317]
**Describe the bug**

If I use `@HOSTNAME@` for EndpointUrl the application starts ok, but it isn't available by this endpoint. I steel forced to use IP address.

**To Reproduce**
1. Generate an application with OpcUaProjectBuilder3
2. Replace 0.0.0.0 by `@HOSTNAME@`
3. Run the app
4. Try to connect with UAExpert

**Expected behavior**

The client must connect to the application by URL `opc.tcp://hostname:port/`

**Logs**
[OpcUaServer.log](https://github.com/ASNeG/OpcUaStack/files/3903891/OpcUaServer.log)
[hostnametcp.pcapng.zip](https://github.com/ASNeG/OpcUaStack/files/3903893/hostnametcp.pcapng.zip)

**Environment (please complete the following information):**
 - OS: Ubuntu-19.10 
 - Version 3.8.0

**Additional context**

In the logs one can see that the server binds a socket with IP `127.0.1.1` but UAExpert is looking for IP 127.0.0.1.

In docker-compose network the application binds the external IP:

```
2019-Nov-29 06:05:37.548068 INF [7f1c3d908700] secure channel endpoint open : Address=<172.30.1.3>, Port=<8889>
2019-Nov-29 06:05:37.548291 INF [7f1c3d908700] open opc ua endpoint : EndpointUrl=<opc.tcp://opcuaserver:8889>, ChannelCount=<0>, SessionCount=<0>
```

**Comment by flipback** [comment]
@huebl, why don't we bind  IP 0.0.0.0 for the hostname?

**Comment by huebl** [comment]
The endpoint url must be a valid address (IP address or domain name), because it is used in certificate checking. The address 0.0.0.0 is not a valid address. In version 3 there is no certificate check. Therefore, we could make an exception for version 3.

In version 4, the following behavior was implemented:

https://github.com/ASNeG/OpcUaStack/issues/115

That would also be a solution for version 3.

**Comment by flipback** [comment]
@huebl, I agree with you that 0.0.0.0 is not a valid IP for the endpoint. I mean not to use it for endpoint, but to bind the listening socket with 0.0.0.0 when the application has `@hostname@` in EndpointURL. Actually, it is what you do in #115.  

I can try to copy this solution into Release 3. Ok?

**Comment by huebl** [comment]
Yes, you can do that.
