### ISSUE TITLE
cannot open shared object file: No such file or directory (libOpcUaStackCore.so.3)

### ISSUE THREAD

**Issue by wedvjin** [ASNeG/OpcUaStack#349]
**Describe the bug**
Hello,
Downloaded and installed OpcUaStack into $HOME/.ASNeG as in docs. When trying to create a project by using OpcUaProjectBuilder3 in $HOME/.ASNeG/usr/bin/ getting the error 
```error while loading shared libraries: libOpcUaStackCore.so.3: cannot open shared object file: No such file or directory```
The required library is located in lib folder as in default install.
**To Reproduce**
1. Download and install OpcUaStack as in docs
2. Try running OpcUaProjectBuilder3
3. Observe error

**Expected behavior**
Create a project

**Logs**
No logs generated

**Environment (please complete the following information):**
 - OS: Kubuntu
 - Version 18.04

**Additional context**
Getting started with ASNeG OpcUaStack, many thanks for conducting such a great work!

**Comment by wedvjin** [comment]
Set correct path as described:
```
$ export PATH=$PATH:$HOME/.ASNeG/usr/bin
$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/.ASNeG/usr/lib/
```
before using OpcUaProjectBuilder3 to create a project.

**Comment by flipback** [comment]
@wedvjin , thank you for the report!
