### ISSUE TITLE
historical parameters

### ISSUE THREAD

**Issue by Tialion** [ASNeG/OpcUaStack#355]
Can you give an example for historical parameters? I tried to take some of yours OpcUaDesigner-master.zip - from file ASNeG-Demo-master\src\ASNeG-Demo\Config\Opc.Ua.NodeSet.HistoricalAccess.xml. All compiled, start, but UA shows the tag as normal

**Comment by flipback** [comment]
Hello @Tialion, thank you for your interest in the project. 

I'm not sure if I've understood your question right, but historical parameters are just VariableNodes that have specific configuration property:

![Screenshot from 2020-04-10 15-30-13](https://user-images.githubusercontent.com/67068/78976365-3a08cc80-7b40-11ea-859f-51c904d3787b.png)

To see historical data in UAexpert you should add 'History Trend View' and drug the historical nodes from Adress Space panel and drop them on the veiw:

![Screenshot from 2020-04-10 15-33-01](https://user-images.githubusercontent.com/67068/78976558-97048280-7b40-11ea-9d8e-1538bd978757.png)

Hope it will help you.

**Comment by Tialion** [comment]
Thanks!
