### ISSUE TITLE
Full implementation of browse request and browse next reques in opc ua server stack

### ISSUE THREAD

**Issue by huebl** [ASNeG/OpcUaStack#496]
Use implementation branch https://github.com/ASNeG/OpcUaStack/tree/498_full_implementation_of_browse_request

**1. Extend Browse Service**

OPC UA Specification: https://reference.opcfoundation.org/v104/Core/docs/Part4/5.8.2/

**Use requestMaxReferencesPerNode parameter from browse request**
Indicates the maximum number of references to return for each starting Node
specified in the request. The value 0 indicates that the Client is imposing no
limitation

ToDo: https://github.com/ASNeG/OpcUaStack/blob/Release4/src/OpcUaStackServer/ServiceSet/ViewService.cpp#L268
- Add requestMaxReferencesPerNode parameter to browseNode function
- Check maximum number of results in referenceDescriptionVec

**Use resultMask Parameter from browse request**
Specifies the fields in the ReferenceDescription structure that should be
returned. 

ToDo: https://github.com/ASNeG/OpcUaStack/blob/Release4/src/OpcUaStackServer/ServiceSet/ViewService.cpp#L309
- Include only the desired attributes in the result. 

**Save unreturned reference descriptions in Map**

ToDo:
- Create a list of unreturned reference descriptions
- Create a unique id for the list (Name of Continuation Point in Browse Result)
- Add the list and the unique id to a continuation point manager (new class). Additional add a expire date to the list (Actual time + 60 seconds?).
- Add the Continuation Point in the browse result

**2. Extend Browse Next Service**

OPC UA Specification: https://reference.opcfoundation.org/v104/Core/docs/Part4/5.8.3/

**Find Continuation Point and create Browse Result**

ToDo: https://github.com/ASNeG/OpcUaStack/blob/Release4/src/OpcUaStackServer/ServiceSet/ViewService.cpp#L161
- Get the Continuation Point Name from the browse next request
- Find Continuation Point in continuation point manager
- Add the next part of continuation points to browse next result
- If there are no more continuation points in the list then delete the list entry.
- check attribute releaseContinuationPoints from browse next request. If required delete coninuation list entry.

**Monitor Lifetime for Continuation Points**

ToDo:
- The coninuation point manager starts a timer each second and checks the expire time for each coninuation point lists. When the time has expired, the continuation list entry will be deleted. 

**3. Add Test Cases**

https://github.com/ASNeG/OpcUaStack/tree/Release4/tst/OpcUaStackClient/ServiceSet

ToDo:
- Add test case to check browse request.
- Add test case to check browse next request.

**Comment by upendar25** [comment]
> * Add the list and the unique id to a continuation point manager (new class)

Where is the object to ContinuationPointManager located in? As per the specification, each server session has at least one continuation point. We are managing that with ContinuationPointManager. But even if we add ContinuationPointManager member to Session.h, I am not sure how to access that from ViewService. Please advice.
