### ISSUE TITLE
Transfer of the information model to the application during startup

### ISSUE THREAD

**Issue by huebl** [ASNeG/OpcUaStack#58]
If a node in the information model is to be accessed, the current reference to the node must be determined via a request. This is expensive. Therefore, it makes sense to pass an interface for the information model to the application.

**Comment by flipback** [comment]
Yes, the transaction model is expensive, but it give us more control and flexibility if we need to change something in the stack or add some features. For example, we could provide access not only to local information model, but to model of the other application or even other application server. 

I suggest discussing it in #59.

**Comment by flipback** [comment]
Hi, @huebl. I suppose we fixed it in #64, didn't we?

**Comment by huebl** [comment]
Yes, this bug is fixed
